### ISSUE TITLE
Metatags to header?

### ISSUE THREAD

**Issue by krionical** [marketempower/axiom#29]
Is there an easy way to add the meta tags to the header? I need to be able to do so to monetize my site.

**Comment by jhauraw** [comment]
https://www.axiomtheme.com/docs/features/#services

**Comment by krionical** [comment]
> https://www.axiomtheme.com/docs/features/#services

Yes but this isn't how I am going about it. I am using coil which has a single meta head tag to be posted in the header. Does one of these allow for that?

**Comment by jhauraw** [comment]
It's probably best to read all the docs. If coil is js then:
https://www.axiomtheme.com/docs/extending/#custom-js

**Comment by krionical** [comment]
> It's probably best to read all the docs. If coil is js then:
> https://www.axiomtheme.com/docs/extending/#custom-js

So, I'm not sure I am being clear. A meta head tag is not exclusively JS.

The meta tag looks like this: 

<meta name="monetization" content="$pay.stronghold.co/1a1b91b23306ab547228c43af27ac0f2411">

I want to add that on all pages that I want to hypothetically receive money on, which unsurprisingly, is all of them. I have read all the "docs" and I did not see where it said one could put a tag such as this. Are you saying that this kind of tag can be put somewhere in the custom js section? If so, I am going to require some clarification.

If you need to see how coil works as a larger overview, the page is here: https://css-tricks.com/site-monetization-with-coil-and-removing-ads-for-supporters/

**Comment by jhauraw** [comment]
Yes we know what meta tags are. Most ad services generate whatever they need via a JS snippet.

Anyway, Axiom doesn't support Coil out of the box. So you would need to use Coil's js snippet if they have one, otherwise you need to override the [baseof.html](https://github.com/marketempower/axiom/blob/master/layouts/_default/baseof.html) with your own as described in Hugo main docs and [here](https://www.axiomtheme.com/docs/extending/#custom-layouts). In the override you can copy/paste your Coil stuff.

**Comment by krionical** [comment]
I learned there was a plugin/module for this, but I simply decided to scrap this theme and go with one with native coil support--I post this mostly for other people who might need to know it.
