### ISSUE TITLE
Axiom + blogdown

### ISSUE THREAD

**Issue by emanuele-guidotti** [marketempower/axiom#3]
Hello, thank you for the theme, it's great!
I'm moving all my tutorials to use your theme, that I really like.

I'm using blogdown to generate the website
https://bookdown.org/yihui/blogdown/other-themes.html
The theme doesn't seem 100% compatible with blogdown but with a couple of fixes in the CSS everything works fine.
https://tutorial.guidotti.dev

It would be great to have a floating TOC like this for the single.html layout
https://storage.guidotti.dev/course/asset-pricing-unine-2019-2020/basic-statistical-concepts-for-finance.html
It's the only thing I feel is missing. Otherwise, I couldn't find a better theme than yours for blogdown.

Of course, feel free to close the issue if not relevant for you.

Best,
-- Emanuele

**Comment by jhauraw** [comment]
Hi Emanuele,

Thank you for the great feedback and I'm glad you are using Axiom for your tuts.

Regarding blogdown: If you have time, please share what changes were needed and I can see about making Axiom work for blogdown out-of-the-box.

Regarding TOC: Are you aware Axiom already supports [Hugo's TOC feature](https://gohugo.io/content-management/toc/)? I realize your request is for a floating one on the left side, but just in case you didn't know.

I see you work with R and very long academic articles where a more advanced TOC is helpful (at least on Desktop, because on Mobile there is no difference). I feel your idea is a great use case for User _override_ or _extension_ of Axiom. Axiom is designed to be modular, and I can think of two ways to get what you request, without it being built into the theme. Sorry, if you already know all this. 👍 

**Override Axiom**: Override the `_default/single.html` view with your own by duplicating Axiom's `_default/single.html`. Code a floating TOC in the view, and add the necessary Javascript to the `custom.js` file:

```
# your site root
/content
/layouts
-- /_default
---- single.html
```

**Extend Axiom**: Assign your piece of Content a specific layout using the `layout` [frontmatter variable](https://gohugo.io/content-management/front-matter#front-matter-variables) such as `layout = "single-toc"` and create a new view:

```
# your site root
/content
/layouts
-- /blog
---- single-toc.html
```

If there are lots of pieces of Content, that would need this view, you could instead create a new Type or Section (like I did for the `axiom-example` website Docs section.

Please let me know what you think of this and if it is useful for you.

Ciao, ~J

**Comment by emanuele-guidotti** [comment]
Hi @jhauraw, thank you for the detailed answer!

Yes, I'm sharing the CSS fixes below but please be aware that they are very quick and dirty fixes. They work in my case but I guess some fine-tuning would be needed in the general case.

Regarding TOC: yes I'm aware Axiom already supports Hugo's TOC feature. I carefully read the documentation :) But it seems that blogdown is somehow overriding the TOC. Also, Rmarkdown provides a friendly [floating TOC parameter](https://bookdown.org/yihui/rmarkdown/html-document.html#table-of-contents).

User extension: it's great your theme is so modular. On the other hand, usually people using blogdown (me too) look for an out-of-the-box solution, and have very little experience with CSS, JS, and web development in general. The typical workflow is the following. Open R studio -> new blogdown website -> insert the theme -> build the website (1-click) -> done! I'm writing to you because 1) I really like the theme, 2) I'm an amateurial web developer and 3) I'm not able to create a nice and clean floating TOC like you could do :) but I'm willing to invest a bit of time to test/help/troubleshoot with blogdown if you wish.

Here the CSS "fixes":

- when you define a header in blogdown using markdown sintax (#), the whole section get wrapped into a `<div>` so your CSS rules do not apply. I had to remove `>` from the CSS. Of course this is not clean and safe
- in blogdown you have an option `highlight` for code blocks. The problem is that your CSS has priority over blogdown's. So I had to remove the background and text color from Axiom CSS. Again, quick and dirty solution

Here it is a snippet of part of my header in blogdown, not using TOC because it is ugly and not floating. 

```r
output:
  blogdown::html_page:
    highlight: breezedark
    toc: false
```

Hope this helps, best
-- Emanuele

**Comment by jhauraw** [comment]
@emanuele-guidotti can you please post your raw article (rmarkdown file) somewhere online so I can look at it? Any one of ur tuts will do. I need to see the **pre** output format, to get a better idea.

**Comment by emanuele-guidotti** [comment]
@jhauraw Yes, please find here the [link to dropbox](https://www.dropbox.com/sh/rsxnp2sfrq21ksn/AABv3vejrIBz4DoMyIcNovg_a?dl=0) where you can find the whole website, including the CSS "fix". It doesn't contain any sensitive information but please let me know when you have downloaded the folder so I can remove it.

**Comment by jhauraw** [comment]
@emanuele-guidotti ok, done. you can delete now. I deleted your comment with link too. So the .Rmd file generates the .html?

**Comment by emanuele-guidotti** [comment]
@jhauraw Great thank you, just removed. Yes the .Rmd generates the html. You can generate and preview the whole website by clicking build -> build website or addins -> serve site (image below).

Oh sorry, I was making some tests and forgot to remove the sitemap.xml from the layouts folder.
Please let me know if I can help further, and thank you for taking care of this request!

![InkedScreenshot (70)_LI](https://user-images.githubusercontent.com/24247667/82616709-47e54f00-9bce-11ea-8a19-305eb2ce7b67.jpg)

**Comment by jhauraw** [comment]
Hi @emanuele-guidotti 

I spent about 5 hours tinkering with RStudio and knitr, but could not find any solutions. Because blogdown outputs a `.html` file from the `.Rmd` file BEFORE it gets to Hugo, there is nothing we can do unless blogdown or knitr provides some options I couldn't find. We need a way to add the `cdata` CSS class to the `<div class="section cdata">` elements, or turn off that dumb wrapper all together. You could post on the blogdown or knitr forums to see if anyone can help.

However, I just released a new version of Axiom v0.6.0 and it has some improvements that will make your website faster at least. Specifically:

- In your Hugo config file turn off syntax highlighting using the new option I describe on the [release page](https://github.com/marketempower/axiom/releases/tag/v0.6.0). Now Axiom will not output any syntax highlighting CSS colors and won't conflict with the Pandoc ones blogdown pollutes everyone of your posts with 😉 (I can't believe blogdown spits out all that Pandoc CSS in EVERY single post, crazy, and so bad).

- I've switched the syntax highlighting library from Javascript Prism to build-side Chroma. Because of this the Prism.js script will no longer load on your pages, this will make your website faster. Since you don't use Hugo syntax highlighting, this is good for you

- You will still need to remove the CSS child combinator selectors (`>`) from the `app.css` file `.cdata` styles. I did find a way to solve this, but it makes Axiom's CSS 20% larger. By adding `.cdata, .cdata > div {}` to the root class definition your div.section are covered. You can do this on your end by re-building the CSS, or just do what you did before and remove the child selectors.

- Re TOC, I didn't get to this yet, but will look more into it, next time I work on Axiom. Gotta do some "real" work for a bit.

**Comment by emanuele-guidotti** [comment]
Hi @jhauraw, thank you for your great work!

I updated the theme and used the hacked CSS. I spend some time too and tried to add `.cdata` or directly drop the `div` from the headings. No success. The only thing I noticed is that the `div` wrapper is not generated if we directly use html tags eg `<h1>` instead of markdown eg `#`. No real solution indeed.

**Idea**: you might want to have a look [here](https://bookdown.org/yihui/blogdown/other-themes.html) and ask for your theme to be listed in the "Simple/minimal themes". This is the very first result on Google for "blogdown themes" and your theme is much better than all the others (yes I tried each single one). Maybe creating a separate repo "axiom for blogdown" would allow to fix the CSS (even if bigger) and increase the usage of the theme. Also the floating TOC would be a nice advantage, not many themes support it. Just an idea, I'm more than happy with it and thanks again for your work!

**Comment by jhauraw** [comment]
Alright sounds good! Thanks for the tip on adding the theme to Blogdown's docs. Take care.

**Comment by jhauraw** [comment]
@emanuele-guidotti I was doing some blogdown CSS research today, and created a beta version of the CSS for blogdown. If you want you can try it. I tested it against your Tuts site and it looks good. Here is the code:
https://gist.github.com/jhauraw/271cfae1a6e52f76eb11c77d2fdc7478

BTW: your current `app.css` file has old CSS in it from Prism.js. Look for class names like `.token` and remove them. This is only relevant if you don't use the CSS I provide in the gist.

The CSS in the gist is BETA, I didn't test it on a blogdown standard page such as About or Contact, and I don't know what the blogdown HTML output looks like on those.

**Comment by emanuele-guidotti** [comment]
@jhauraw Sorry for the late reply. I just tried it out. It seems that the style is not applied to content without a previous `h` tag. [Here](https://www.dropbox.com/s/pnqrujseunpb8r7/screencapture-127-0-0-1-4321-h83h5-2020-05-27-17_27_58.pdf?dl=0) a screenshot. I'll delete it from dropbox when you have done (no hurry).

**Comment by jhauraw** [comment]
Ok thanks for trying. I'll keep working on it. You can delete.
