### ISSUE TITLE
Support for page ressources

### ISSUE THREAD

**Issue by cmlnet** [marketempower/axiom#7]
While I really enjoy your theme I would greatly appreciate if it would support [page resources](https://gohugo.io/content-management/page-resources/).

Maybe I am missing something, but pictures and other stuff have to be placed in the static folder so [page bundles](https://gohugo.io/content-management/page-bundles/) can't be used.

**Comment by jhauraw** [comment]
Hi, glad you like Axiom and use it. Thank your for your feedback.

Page resources can be used in so many ways, such as to create a list of page attachments like when providing a list of PDFs for download. This would be a custom specific layout partial just for this one single use case and cannot be done in Markdown (at least not marked up with HTML). So it would have to be a partial with a companion shortcode. This is not something Axiom would provide, but rather something the user would create in his/her own `/layouts` directory as an extension to Axiom.

There is nothing preventing you from storing your images and other resources in a Page Bundle right now. Just use relative URLs when creating a Markdown image tag. For example, this works fine:

```
content/
├── posts
│   ├── my-post
│   │   ├── index.md
│   │   └── bundled-image.png
```

`/content/posts/my-post/index.md`:
```bash
+++
title = "My Post"
+++

![](bundled-image.png)
```

Axiom does lean more toward the opinion of not storing assets in Git because it's not great to have huge repo's full of images (assuming the user uses CI and serverless deploy styles). That's why Axiom offers CDN support.

Can you be more specific as to exactly how you would want Axiom to change?

**Comment by cmlnet** [comment]
Thank you for the quick replay. I am sorry if I have missed something or my initial post was not clear enough.

1. What I would specifically use page resources for is the featured image. At the moment the front matter `feature: image/cover.jpg` will only look for that file in the `static` folder. However, I would like to store images alongside the .md file of the article, i.e. in a page bundle.

2. Additionally, I would like `{{< figure src="images/logo.png" >}}` to look for the image in the page bundle as well. This is the behaviour of the default figure shortcode as far as I know.

While I can solve the second by overwriting the figure shortcode with a customn on, I was not able to solve the first issue. Probably because of my limited knowledge of Go.

I can totally understand if you want Axiom to stick to the actual behaviour and thus close the issue.

**Comment by jhauraw** [comment]
Hi, both #1 and #2 that you mention above currently both work as you describe. Using the same example setup I listed in my previous comment, this works using the Axiom Example repo:

```+++
date = 2020-07-08T16:00:00Z
lastmod = 2020-07-08T16:00:00Z
author = "default"
title = "Bundled Image Example"
feature = "my-post/bundled-image.png"
+++

{{< figure src="my-post/bundled-image.png" caption="Bundled Image." >}}
```

It also works just fine when nesting the resources in an images folder like in your example. Though I would recommend against using a separate images folder in the bundle, IMHO it's redundant and unnecessary, esp. if a bundle is just two resources (an .md and a feature image).

Axiom uses Hugos `relref` on all local resources as is recommended by Hugo, so I think maybe that is what is different from your example and mine. I've put the post name in front. Same as if in the `static` dir if you nested images like this: `static/images/posts/my-post.png` your Page Param for `feature` would need to be `images/posts/my-post.png`. So the behavior is consistent, the key being "root relative" URLs vs. "base relative".

Let me know how that goes for you and if you have any suggestions regarding that.

Also, note that there is a new Shortcode called `page-resource` that allows you to grab `Page` type resources from the bundle and include them in the Content. So you could have a bundle with a snippet like `data-table.md` and put in inline in your Content like:

`{{% page-resource "data-table" %}}`

or, if it's an `.html` file, using the other Shortcode escapes `<` and `>`:

`{{< page-resource "data-table" >}}`

**Comment by cmlnet** [comment]
Thank you again. Indeed the difference was the post name and with this it works just fine. I was just irritated because in the Ananke theme this is not necessary.

Anyway, thank you for your patience and the detailed answers!
